---
title: "Project 1: History of Philosophy"
author: "Kieu-Giang Nguyen"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(beeswarm)
library(data.table)
library(dichromat)
library(dplyr)
library(factoextra)
library(fmsb)
library(ggplot2)
library(gridExtra)
library(qdap)
library(quanteda)
library(quanteda.textstats)
library(RANN)
library(RColorBrewer)
library(readtext)
library(rvest)
library(scales)
library(sentimentr)
library(stopwords)
library(stringr)
library(syuzhet)
library(textreuse)
library(tibble)
library(tidytext)
library(tidyverse)
library(tm)
library(topicmodels)
library(wesanderson)
library(wordcloud)

source("../lib/plot_stacked.R")
source("../lib/speech_funcs.R")
source("../lib/helper_funcs.R")
```

```{r, eval=FALSE, message=FALSE, warning=FALSE}
# df <- read.csv("../data/philosophy_data.csv")

# Read data using data.table to decrease runtime
df <- data.table::fread("../output/philosophy_data_table.csv")

df <- df %>%
  group_by(school) %>%
  mutate(mode_date = find_mode(original_publication_date)) %>%
  ungroup() %>%
  mutate(school = ifelse(school == "german_idealism", "German Idealism", str_to_title(school)),
         school_ordered = reorder(factor(school), mode_date, mean, order = TRUE))

palette <- get_palette(length(unique(df$school)))
```

# Overview

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}
par(mfrow = c(4, 4))

i <- 0
for(s in levels(df$school_ordered)) {
  docs <- Corpus(VectorSource(df[df$school == s, ]$sentence_str)) %>%
    tm_map(tolower) %>%
    tm_map(removePunctuation) %>%
    tm_map(removeNumbers) %>%
    tm_map(removeWords, stopwords("english")) %>%
    tm_map(stripWhitespace)
  
  tdm <- TermDocumentMatrix(docs)
  tdm_tidy <- tidy(tdm)
  tdm_overall <- summarise(group_by(tdm_tidy, term), sum(count))
  
  i <- i + 1
  plt_title <- s
  wordcloud(tdm_overall$term, tdm_overall$`sum(count)`,
            scale = c(5, 0.5),
            max.words = 200,
            min.freq = 1,
            random.order = FALSE,
            rot.per = 0.3,
            random.color = FALSE,
            colors = palette[i])
  mtext(plt_title, side = 3)
}
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}
df %>%
  unnest_tokens(bigram, sentence_str, token = "ngrams", n = 2) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>%
  filter(!word1 %in% stopwords::stopwords(source = "snowball")) %>%
  filter(!word2 %in% stopwords::stopwords(source = "snowball")) %>%
  filter(!is.na(word1)) %>%
  filter(!is.na(word2)) %>%
  unite(bigram, word1, word2, sep = " ") %>%
  group_by(school_ordered, bigram) %>%
  summarize(n_bigram = n()) %>%
  slice_max(n_bigram, n = 10) %>%
  mutate(bigram = reorder_within(bigram, n_bigram, school_ordered)) %>%
  ggplot(aes(x = bigram, y = n_bigram, fill = school_ordered)) +
    geom_bar(stat = "identity", show.legend = FALSE) +
    facet_wrap(~school_ordered, scales = "free") +
    coord_flip() +
    scale_x_reordered() +
    scale_fill_manual(values = get_palette(length(unique(df$school)))) +
    labs(title = "Top 10 Bigrams by School", x = element_blank(), y = "Count") +
    theme_classic()
```

# Philosophy speech

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}
df %>%
  ggplot(aes(x = sentence_length, fill = school_ordered)) +
    geom_histogram(binwidth = 2, size = 0.25, show.legend = FALSE) +
    xlim(0, 500) +
    facet_grid(rows = vars(school_ordered)) +
    scale_fill_manual(values = palette) +
    labs(title = "Sentence Length by School", x = "Word count", y = "Sentence count") +
    theme_classic()
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
df_avg_length <- df %>%
  group_by(original_publication_date) %>%
  mutate(avg_length_time = round(mean(sentence_length), 0)) %>%
  ungroup() %>%
  group_by(school_ordered) %>%
  mutate(avg_length_school = round(mean(sentence_length), 0)) %>%
  ungroup() %>%
  distinct(original_publication_date, school_ordered, mode_date, avg_length_time, avg_length_school)

ggplot() +
  geom_line(data = df_avg_length, aes(x = original_publication_date, y = avg_length_time), stat = "identity") +
  geom_bar(data = distinct(df_avg_length, school_ordered, mode_date, avg_length_school), aes(x = mode_date, y = avg_length_school, fill = school_ordered), stat = "identity", width = 5) +
  scale_fill_manual(values = palette) +
  labs(title = "Average Sentence Length", x = "Year", y = "Word count", fill = "School") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal")
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
df_distinct_word <- df %>%
  unnest_tokens(word, sentence_str) %>%
  filter(!(word %in% stopwords::stopwords(source = "snowball"))) %>%
  group_by(original_publication_date) %>%
  mutate(ndistinct_word_time = length(unique(word))) %>%
  ungroup() %>%
  group_by(school_ordered) %>%
  mutate(ndistinct_word_school = length(unique(word))) %>%
  ungroup() %>%
  distinct(original_publication_date, school_ordered, mode_date, ndistinct_word_time, ndistinct_word_school)

ggplot() +
  geom_line(data = df_distinct_word, aes(x = original_publication_date, y = ndistinct_word_time), stat = "identity") +
  geom_bar(data = distinct(df_distinct_word, school_ordered, mode_date, ndistinct_word_school), aes(x = mode_date, y = ndistinct_word_school, fill = school_ordered), stat = "identity", width = 5) +
  scale_fill_manual(values = palette) +
  labs(title = "Number of Distinct Words", x = "Year", y = "Word count", fill = "School") +
  theme_classic() +
  theme(legend.position = "bottom", legend.direction = "horizontal")
```

# Sentiment analysis

```{r, message=FALSE, warning=FALSE}
emotions <- data.table::fread("../output/emotions.csv")
df_emotions <- cbind(df, emotions)
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=6}
par(mfrow = c(4, 4))

i <- 0
for(s in levels(df$school_ordered)) {
  emotions_by_school <- df_emotions %>%
    mutate(school = ifelse(school == "german_idealism", "German Idealism", str_to_title(school))) %>%
    filter(school == s) %>%
    dplyr::select(anger, anticipation, disgust, fear, joy, sadness, surprise, trust) %>%
    bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total")) %>%
    slice_tail(n = 1) %>%
    as.data.frame()

  emotions_by_school <- rbind(rep(max(emotions_by_school), 8), rep(min(emotions_by_school), 8), emotions_by_school)
  
  i <- i + 1
  plt_title <- s
  radarchart(emotions_by_school, title = plt_title,
           pcol = palette[i], pfcol = alpha(palette[i], 0.3), plwd = 2,
           cglcol = "grey", cglty = 1, axislabcol = "grey", caxislabels = seq(0,20,5))
}
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
# Default colors: "#F8766D", "#00BFC4"
df_emotions %>%
  group_by(original_publication_date) %>%
  summarize(positive = mean(positive),
            negative = mean(negative)) %>%
  pivot_longer(!original_publication_date, names_to = "emotion", values_to = "avg_count") %>%
  ggplot(aes(x = original_publication_date, y = avg_count, color = emotion)) +
    geom_line(stat = "identity") +
    labs(title = "Emotional Valence over Time", x = "Year", y = "Average count", color = "Emotion") +
    # scale_color_manual(values = wes_palette("Rushmore1", 8, type = "continuous")) +
    theme_classic()
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
df_emotions %>%
  group_by(original_publication_date) %>%
  summarize(anger = mean(anger),
            anticipation = mean(anticipation),
            disgust = mean(disgust),
            fear = mean(fear),
            joy = mean(joy),
            sadness = mean(sadness),
            surprise = mean(surprise),
            trust = mean(trust)) %>%
  pivot_longer(!original_publication_date, names_to = "emotion", values_to = "avg_count") %>%
  ggplot(aes(x = original_publication_date, y = avg_count, color = emotion)) +
    geom_line(stat = "identity") +
    labs(title = "Sentiment over Time", x = "Year", y = "Average count", color = "Emotion") +
    scale_color_manual(values = wes_palette("Rushmore1", 8, type = "continuous")) +
    theme_classic()
```

# Similarity analysis

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
corp_sentence <- corpus(df, text_field = "sentence_str")

dfmat_sentence <- corp_sentence %>%
  quanteda::tokens(remove_punct = TRUE, remove_symbols = TRUE) %>% 
  dfm() %>%
  dfm_remove(pattern = stopwords("en"))

# dfmat_author <- dfm_group(dfmat_sentence, groups = author)
# tstat_dist <- as.dist(textstat_dist(dfmat_author))
# author_clust <- hclust(tstat_dist)
# plot(author_clust)

dfmat_school <- dfm_group(dfmat_sentence, groups = school_ordered)
tstat_dist <- as.dist(textstat_dist(dfmat_school))
school_clust <- hclust(tstat_dist)
plot(school_clust)
```

```{r, message=FALSE, warning=FALSE, fig.width=6, fig.height=3}
emotions_by_school <- df_emotions %>%
  group_by(school_ordered) %>%
  summarize(
    anger = mean(anger),
    anticipation = mean(anticipation),
    disgust = mean(disgust),
    fear = mean(fear),
    joy = mean(joy),
    sadness = mean(sadness),
    surprise = mean(surprise),
    trust = mean(trust)
  ) %>%
  as.data.frame()

rownames(emotions_by_school) <- as.character((emotions_by_school[, 1]))
kmeans_res <- kmeans(emotions_by_school[,-1], iter.max = 200, 5)
fviz_cluster(kmeans_res, stand = FALSE, repel = TRUE,
             data = emotions_by_school[,-1], xlab = "", xaxt = "n",
             show.clust.cent = FALSE, ggtheme = theme_classic())
```